# Site settings
name: Dinesh Kumar
title: Dinesh Kumar | UI/UX Designer & Open-Source Contributer
description: Design-minded, detail oriented software engineer passionate about combining beautiful code with beautiful data.
url: http://eldinesh.is-a.dev
baseurl: ""
email: dseera6@gmail.com
cover: http://eldinesh.github.io/img/og.png
logo: https://eldinesh.github.io/img/emojis/technologist.png
resume: https://www.linkedin.com/in/eldinesh/
social:
  - title: email
    url: mailto:dseera6@gmail.com
  - title: twitter
    url: https://twitter.com/eldineshk
  - title: instagram
    url: https://instagram.com/eldineshk
  - title: telegram
    url: https://t.me/eldinesh
  - title: github
    url: https://github.com/eldinesh
  - title: linkedin
    url: https://www.linkedin.com/in/eldinesh

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
